language: python
python:
- 3.5
install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- npm install -g npm
- pip install -e .[tests]
- sudo ./powebscr/install_libicu52.sh
- npm install
script:
- py.test tests
- npm run build
- npm run test-jest
# check static files
- file snoin/web/static/dist/node_modules/html5shiv/dist/html5shiv.min.js
- file snoin/web/static/dist/node_modules/html5shiv/dist/html5shiv-printshiv.min.js
- file snoin/web/static/dist/node_modules/respond.js/dest/respond.min.js
- file snoin/web/static/dist/node_modules/respond.js/dest/respond.matchmedia.addListener.min.js
# lint
- hooks/pre-commit
after_success:
- python -m powebscr
- deploy/deploy.sh
notifications:
  irc:
    channels:
    - irc.ozinger.org#snoin-dev
    on_success: change
    on_failure: always
env:
  global:
  - TRAVIS_NODE_VERSION="5"
  # DEPLOY_ADDR
  - secure: P5YY7LSlofgSvvyAnILgiq7/Sq1EGEUHBHdXISodZINTBwRsHbo5qJh4tzKgPdxYvVOaiAnXBMDUu0zLWZorYhdibniHJPyQJUmDz05B/nRs0C3WjwBRPWClCcn24YNraSFEXevKnsxyy1JQe+JgD/72O5Lef2/XdzGPxobUbp/NxMALbG0SGBzq+XBXXI0U9rU+b19LJEvqZY/2DDYwHctV65jojQzcE1lCivXM3AEG1y1625yEdHe7ZbXybkfOYIiI4vwguqHFO/RmEAqUllot+mMErid4zIZUvqdMVvAJ2izo3FK7dnQQ+Ms9mCG7WzsYjcbcVo3eFIkmLw8tze3eQwyZztKQPl+T6W9d0jb7ID7BxPsYRryQB08zfrWbN16u6h8y7C7sjznRqkkFEBfJ2d3xcHiM4y+btep3tBTtElENTATbAY+qqn8lfAU2iMWgRFSiL3MqPRkh8drENg4TbhmP2Mk9RGfZIiiTq8xPs8b50H8/eiZwduhVK27IXOiShSWtyCwE+hv1K4CBv/go9Ip7y8MY0diuHFLivDljy2BK0ZERmy9MKavFDLJFLpJyjcupFIopBfu5yzGjH5r//nLChoR5H5v1cz5aN8yvPZWmCyUs+De38FIjosKmgyvfGUn+Cd5QRzQ1gxYAig2e8yX3nOvSH1Km7N2cVlA=
  # DEPLOY_SERVER_RESTART
  - secure: yyH/DIs8WDrHVMHJUyI+Dl74S7wSRl+V1V8RIEf5TNL4QinckMhMjIEc1rSpJ3FoPF6bSp8s3Bwuq8Iad1kPkMyoGvl3tPoOclToUn/B95GsleS2M8IPoVAa8yvgcjIzwYGLut+dL0ITre+8H7X7vDeJf6c4xmEH5eyg5302BNkZ54KnQ56wexJNdLK5paPmcCdaYOt06VpIvgakudGjNXNCgh5xuOXXi3cxc/rltTq8PkzqFlZ3+92IUGHpqn3bo8SVWSEHjTFkuNE7loov7Y2JcpYOApchlooC/qnAxDmBlvT5v0otwxxRVEiT8Ckoab9YPdR292AjuKezFHXed3IFNnGo3RNO0JwgEtEO7LhnfTmpVlUdWdJ4MneLqVoLJYFnfE1/eaLmLH/6jrW/yEm+9lkEXNIag9qLQvM5aVQ532g4jjga4usjtRquqJsS9gtDAOcCq16FM/O0XTAgm2PRoSJFBN7PUs0kehdeVEoLNCprcHUA8Aqm/6tcZo9lEPwC/FdV1gJId0vhuIJjn9v6L9pfKmq5CBoIoh9mk4VqBCaMa8mGsWuuhJEigfB2yuxAKOzbGEMCXmb6RrcBLnjDWmM1rtqxljGOCd9hX2I8UUBCj9ldcB7g/WtuJfKStsFJS+hoPNfQz3ecyt8F43nvjS+/0lWxKVCSrhZQVpk=
