language: python
python:
- 3.5
install:
- pip install -e .[tests]
- ./powebscr/setup-legacy.sh
- npm install
script:
- py.test tests
- npm run build
# lint
- hooks/pre-commit
- python ./powebscr/powebscr/legacy/__main__.py
after_success:
- deploy/deploy.sh
notifications:
  irc:
    channels:
    - irc.ozinger.org#snoin-dev
    on_success: change
    on_failure: always
env:
  global:
  # DEPLOY_ADDR
  - secure: t46vHZpdyQk5kZhRImsKSGpIsNiG6di5xsqhS6KOZCxzrljpQG9bM9e6TzFdZ4L7f0SHthj205bIgxyTxbg+2C4zkbY8sqgaNQBlc3a9WoJ80NvaoHIu4kjAlnvrO2nSIHPpBF9aX1fwX6zruH6qJhpNOny6DRbJYyRP+8wmMZSZYXSloO33pwAbcZSfEeNnUVjDeQaV+DJ4w7bPSspdtsOHoRFiyxlKGShavrPjYhHvycdOSGI0VpeMq12cc49kgXFcCmfJrsGKoEoVCmMIVBbEwxQV4jotdDvqkxrBk36bl9MUoCCDYVtTF1FCfPGd6eW2PW2jcxIan5oQFedTtIF68oTGF3lklB+nGafcpTdQLRfU8qF6YCJtAfqxoDwE2oUQy5UB0mQcWlJoiWWwLaUAuzol7URvua2DctUoR0FsLuD4KrmXa/udDvkk3MRo355bpsFd4hlWV3GGgqInHl79nxlUV92R+EKNW/nDIilnroUZ1npN0zmvVSI9Ivx3dKKVJGT4s3DY7mlbrbWk8Nwhgcku462BH8OlMqaTKyLsMoDKnF5JK5nMBcqPAtXzX3hR68kUvzdJ/Jq9ncsxPJuTXG4WOY5xra6yoE2hIFSCPe0s6BC60InVm1fayyaVtbhcrdGhmX/q51+v1wPymCLaVNqV5kjI7DL09ESvFtQ=
  # DEPLOY_SERVER_RESTART
  - secure: KvMnZ3tEyEXflHeTn8XEHQcKiZCUh6dUmkgzLGoV1iUHnwEDYnhIYg/NARdpsttm1SkQ648s9+UScTPsh+v7RNqPjZv4qFRlPbBQ8ZWVxmnLcUdV9TRLdmOSw9HR/CMFsZJi/E4XnBmpXqXv+OZ2uJXv40rvf709CO6xV2oGtLcpNpCUPR1p1se93mqayBempgJYAUPWuksiR67pB2ON8W15ZH7HLOhHfEfSzU2EqlfFc95umGebyGo/wKap5xmRvYKzM4Zm20x9/eVJdSqVB3fNch8acH4DjnYDiI6ZR3oZGUt4WIsXTRyRyjPj5YqIc0Z+G0F9Us13SMuFw2d2AyRUmX5n6h1JBVOYZEwShBBUVrIKygLqA0dEtODySsiZ200zjEAo+Q0zVPlpko1kE24DjUDIeYNFwND5nzE6yPKX1oClYK51rwVYZVqmqrLFiu4IVANX9pWFNL3H02M/RvhG10gyXm1huboSQOrdTEYACf64PZ3XZ3yeG96zgcAV+nXYBfa6jmMRbrbwcwYq/gEoMZ2U7mYqASwDlAYmzdsb9NtozDlAgZY/bH13XiWhASmG7ENMvVcVenCILZdXpUc+HP2bfG3KIiIXhXpv7xPt/CvJ6rYuOAE06ZuSpyLFD0Ub9ANNWBLUaSlQKzgPsrEwYDHdABYPgDwY/Xh9HJs=
