language: python
python:
- 3.5
addon:
  firefox: latest
install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- npm set progress=false
- npm install -g npm
- pip install -e .[tests]
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- py.test tests
- npm run build
- npm run test-karma-ci
# check static files
- file snoin/web/static/dist/node_modules/html5shiv/dist/html5shiv.min.js
- file snoin/web/static/dist/node_modules/html5shiv/dist/html5shiv-printshiv.min.js
- file snoin/web/static/dist/node_modules/respond.js/dest/respond.min.js
- file snoin/web/static/dist/node_modules/respond.js/dest/respond.matchmedia.addListener.min.js
# lint
- hooks/pre-commit
after_success:
- deploy/deploy.sh
notifications:
  irc:
    channels:
    - irc.ozinger.org#snoin-dev
    on_success: change
    on_failure: always
env:
  global:
  - TRAVIS_NODE_VERSION="5"
  # DEPLOY_ADDR
  - secure: VKKKlXwKaiJZFSOaG9jVEhVD/y3GhJYt81R0jRdIkW9JSe16Uwm0jqTRyCyFfnnOM4/ELxaDh12ubOWb76jLT7kPK3P5kI3pf8ufNlW+uFqL1CfTGCN0Z3/koVPb9CiNdwyDALZS5YAIp8QerguIjGle9D5j9EeP2TV2wTM8OeLpkDyKsOQp6iB3i9e7qa69eJKaJ+SdJs38gUOYS4TfyXiFxL718zzKlDrdeGwNpvg7QzFvGOvyWn5qC1KS9T3lszXdFejlAB8APICAAlUTQ44M2XM0ux/SJ0V7TZ7T0qahiTyoVj0DX9Xqg5ypabktimh912syPZapbVMa22he2H3fbu4vsGRqdVWiG0L9umQmgOYpArVae4u7jUzWMQ32FPrOPAHGIh+iQWzu7s8fQTND5If5buhcaxXcjn8Ah+ffHngn3VwzhJbTnnfGLzccJCbW7MBL4CfGWGTIZ9G+73nIWrKZTs8ASGe7kA7rQgHzYxD3Ij/ilPhASj1wh45oDjntsKlz9dMXRCzG+ILFVA9q8usKeJI50WjtQ+eojOTrfPBUP00w8CxI1pwB7rwgw4MsBz4Oe5heBWZusSbXeQhCDzhND6Bi0h6QCW0c/g/4qdhnWxKTFdCWlMDKr85lWPisnu0Lo0y8EyYTfMIqJbkeBeoRdMEFRmc98j8XcGs=
  # DEPLOY_PORT
  - secure: xw7ZVyaSvo87/dxiDB2cE4ME5Wds/4l7STB2QMouKBuAM6GmVIkpnH5+TQR4PHFAqONjZAHaGoVnin5fG7IfazKGqqEb5UnnYbqZyrFlbXCqbPxledBpgSELWokinVZCVHLAuDMF1YIjY4aa83t+1wO393yP2dbfPHLJTssNDzUeS9GFIN9zEDEcVWzVudutYuXw5j5+OCmMNWy61CPdxwQEVi1hK4OFVXgafkL/rsZka9jiGI8kIqP/0JocBzIzvqABr85JpDRgb8n9iEDYtxi8XltdjZljqL583JnP9bG73/QinHzgq9vRBqr+KPoo5L42MR0OUHbx8U0skZz6E0Dqnp8GFEXBDxpUOtIRuctQQTagOVpnaSERl3J8shQbb7xzb4sCW7q4UVP5nP+matzLq0TVcnVF2NLCHn+8m1a8W12MhYA8yUCEgthSY8NmOQwA74eIIBYpws2HNRLIRxFHw1o9qS+UwsPml6WTVr7+AIqJkOZUmVEY2V32gon6+5+q2qIvgckLKcYLmeF/WwequRFK/qlye1cC4L3/xqkMBsPsxY+NiT2jeYHYSExlRPuVcMrsSvzk/KrSfR3oIvlhMp6VWytOzpSacN3no8+KmnMmuhmrsqs/0hBdjoh6BXyrbvApJhEkI2vp9smpF5Ve69GYIYRCtpwiZorIpKE=
  # DEPLOY_SERVER_RESTART
  - secure: yyH/DIs8WDrHVMHJUyI+Dl74S7wSRl+V1V8RIEf5TNL4QinckMhMjIEc1rSpJ3FoPF6bSp8s3Bwuq8Iad1kPkMyoGvl3tPoOclToUn/B95GsleS2M8IPoVAa8yvgcjIzwYGLut+dL0ITre+8H7X7vDeJf6c4xmEH5eyg5302BNkZ54KnQ56wexJNdLK5paPmcCdaYOt06VpIvgakudGjNXNCgh5xuOXXi3cxc/rltTq8PkzqFlZ3+92IUGHpqn3bo8SVWSEHjTFkuNE7loov7Y2JcpYOApchlooC/qnAxDmBlvT5v0otwxxRVEiT8Ckoab9YPdR292AjuKezFHXed3IFNnGo3RNO0JwgEtEO7LhnfTmpVlUdWdJ4MneLqVoLJYFnfE1/eaLmLH/6jrW/yEm+9lkEXNIag9qLQvM5aVQ532g4jjga4usjtRquqJsS9gtDAOcCq16FM/O0XTAgm2PRoSJFBN7PUs0kehdeVEoLNCprcHUA8Aqm/6tcZo9lEPwC/FdV1gJId0vhuIJjn9v6L9pfKmq5CBoIoh9mk4VqBCaMa8mGsWuuhJEigfB2yuxAKOzbGEMCXmb6RrcBLnjDWmM1rtqxljGOCd9hX2I8UUBCj9ldcB7g/WtuJfKStsFJS+hoPNfQz3ecyt8F43nvjS+/0lWxKVCSrhZQVpk=
