language: python
python:
- 3.5
install:
- pip install -e .[tests]
- pip install -e .[webscr]
script:
- py.test tests
after_success:
- python powebscr.py
notifications:
  irc:
    channels:
    - "irc.ozinger.org#snoin-dev"
    on_success: change
    on_failure: always
