language: python
python: 3.8
sudo: false
before_install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install stable && nvm use stable
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn
- pip install -e .[tests]
script:
- pytest tests
- yarn run build-product
# lint
- flake8 ./snoin ./tests
- yarn run lint-js
- yarn run lint-style
- gixy deploy/nginx.conf
cache:
  directories:
    - $HOME/.cache/pip
    - node_modules

